// This file was automatically generated by the Ant build process.
// Your edits will be lost when you run Ant again.

package org.thdl.util;

/** Contains methods for determining the time at which this class
    was compiled.  This is useful for filling out bug reports about
    nightly builds.  This class is not instantiable. */
public class ThdlVersion {
    /** Do not instantiate this class. */
    private ThdlVersion() { }

    /** Returns a string indicating the time this program was compiled. */
    public static String getTimeOfCompilation() {
        return "4-June-2013 03:02 PM";
    }
}
